# Generated by Django 3.0.7 on 2020-07-07 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre:')),
                ('description', models.TextField(max_length=450, verbose_name='Descripción:')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código ciudad')),
                ('name_city', models.CharField(blank=True, max_length=210, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['id_city'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_identification', models.CharField(choices=[('NIT', 'Número de identificación tributaria'), ('CC', 'Cédula de ciudadanía'), ('DIE', 'Documento de identificación extrajero'), ('PP', 'Pasaporte'), ('CE', 'Cédula de extranjería'), ('TE', 'Tarjeta de extranjería'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil')], default='', max_length=210, verbose_name='Tipo de identificación')),
                ('identification', models.CharField(max_length=10, unique=True, verbose_name='Identificación')),
                ('dv', models.CharField(max_length=2, verbose_name='Dv')),
                ('name_client_1', models.CharField(max_length=150, verbose_name='Nombre')),
                ('name_client_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo nombre')),
                ('last_names_cliente', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('type_person', models.CharField(choices=[('Persona Jurídica', 'Persona Jurídica'), ('Persona Natural', 'Persona Natural')], default='', max_length=210, verbose_name='Tipo de persona')),
                ('type_responsibility', models.CharField(choices=[('Régimen Común', 'Resposable de IVA'), ('Régimen Simplificado', 'NO Resposable de IVA')], default='', max_length=210, verbose_name='Tipo de responbilidad')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=210, verbose_name='Correo')),
                ('tel_1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono 1')),
                ('tel_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono 2')),
                ('mobile', models.CharField(max_length=10, verbose_name='Celular')),
                ('client', models.BooleanField(verbose_name='Cliente')),
                ('provider', models.BooleanField(verbose_name='Proveedor')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.City')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código país')),
                ('name_country', models.CharField(blank=True, max_length=210, null=True, verbose_name='País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'ordering': ['id_country'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Contact')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('reference', models.CharField(max_length=10, unique=True, verbose_name='Referencia')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='Costo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='Precio')),
                ('description', models.TextField(max_length=450, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('inventory', models.BooleanField(verbose_name='¿Inventariable?')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dptos',
            fields=[
                ('id_dpto', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código dpto')),
                ('name_dpto', models.CharField(blank=True, max_length=210, null=True, verbose_name='Departamento')),
                ('id_country_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Country')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['id_dpto'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Dptos'),
        ),
        migrations.AddField(
            model_name='city',
            name='id_dpto_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Dptos'),
        ),
    ]
